baseURL = "http://example.org/"
languageCode = "es"
title = "AExperience"
theme= "restaurant-hugo"
summaryLength = "7"
# Menu
[menu]

	[[menu.nav]]
    name = "Inicio"
    URL = "/"
    weight = 1
    post = "<All>"
    title = "All"

    [[menu.nav]]
    name = "Espacios"
    URL = "#espacios"
    weight = 2
    post = ""
    title = "main"

    [[menu.nav]]
    name = "Bonos"
    URL = "#bonos"
    weight = 3
    post = ""
    title = "main"

    [[menu.nav]]
    name = "Newsletter"
    URL = "#subscribe"
    weight = 4
    post = ""
    title = "main"

    [[menu.nav]]
    name = "Contacto"
    URL = "/contactos"
    weight = 5
    post = "<All>"
    title = "All"

    [[menu.nav]]
    name = "Blog"
    URL = "/blog/"
    weight = 7
    post = "<All>"
    title = "All"
    
    [[menu.nav]]
    name = "Acceso Usuario"
#    URL = "http://192.168.0.14:8088/login"
    URL = "http://192.168.0.82:8088/login"
    weight = 8
    post = "<All>"
    title = "All"

# Global Settings
[params]
logo = "images/logo.jpg"

[params.inicio]
enable = true
[params.heroImg ]
url =  "images/castillo1.jpg"

#Slider
[params.slider]
enable = true

#gallery item
[params.gallery]
enable = false
title= "Próximos <span>Eventos</span>"

[[params.gallery.item]]
img = "images/slider/playmobil.jpg"

[[params.gallery.item]]
img = "images/slider/medieval2.jpg"

[[params.gallery.item]]
img = "images/slider/contempopranea.jpg"

[[params.gallery.item]]
img = "images/slider/balonmano.jpg"

[[params.gallery.item]]
img = "images/slider/feriaganao.jpg"

[[params.gallery.item]]
img = "images/slider/carrera.jpg"

[[params.gallery.item]]
img = "images/slider/semanasanta.jpg"

[params.miperfil]
enable = true
title= "Mi <span> Perfil</span>"
bgImage = "images/cooker-img.png"
description= "Mis Bonos - Mis Reservas - Mis Datos"

#bonos Menu
[params.bonos]
enable = true
title = "Bonos <span>Piscina</span> y <span>Gym</span>"
description= "Las instalaciones de la piscina municipal estarán abiertas en verano de lunes a domingo en horario de 12:00 - 21:00 h. Y las instalaciones del gym en Horario de Verano: Lunes de 18:00 - 22:30 h, Martes a Viernes de 12:00 - 14:00 h / 18:00 - 22:30 h, Sábado de 12:00 - 14:00 h. Horario de Invierno: Lunes de 17:00 - 22:00 h, Martes a Viernes de 12:00 - 14:00 h / 17:00 - 22:00 h, Sábado de 12:00 - 14:00 h."
subtitle = "Precios"

[[params.bonos.item]]
title="70 entradas"
description= ""
bonos = "50.00 €"

[[params.bonos.item]]
title="25 entradas"
description= ""
bonos = "25.00 €"

[[params.bonos.item]]
title="10 entradas"
description= ""
bonos = "12.00 €"

[[params.bonos.item]]
title="Diaria Adulto"
description= ""
bonos = "3.00 €"

[[params.bonos.item]]
title="Diaria Menores y Pensionistas"
description= "Se entiende por menores a las personas que tengan menos de 15 años. Los niños hasta 4 años tendrán entrada gratuita."
bonos = "1.50 €"


#subscription
[params.subscription]
enable = true
title= "SUBSCRIBETE a nuestra <span>NEWSLETTER</span>"
description = "Subscríbete para no perderte nada y estar al día de todo lo que pase en Alburquerque"

#Mailchimp subscription configuration
#formAction = "http://192.168.0.14:8088/tiponoticias"
formAction = "http://192.168.0.82:8088/tiponoticias"
formName = "b_f95ece2732a6e9925f2e70a61_b1e227529e"


[params.contactos]
enable = true
title= "<span>Contacto</span>"
subtitle= "Escríbenos"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod"


[params.espacios]
enable = true
title = "<span>Reserva</span> de <span>Espacios</span>"

#blog
[params.blog]
enable = true
title= "<span>Blog</span>"
subtitle = "Ultimas Noticias"


#Footer
[params.footer]
enable = true
contactoInfoTitle = "INFO DE <span>CONTACTO</span>"
espaciosTitle = "MI <span>PERFIL</span>"
galleryTitle = "Fotos <span>Eventos</span>"
socialTitle = "REDES <span>SOCIALES</span>"

[[params.footer.contactoItem]]
title="Teléfono"
icon = "fa fa-mobile"
content = "924 40 00 00 - 924 40 00 01"

[[params.footer.contactoItem]]
title="Fax"
icon = "fa fa-phone"
content = "924 40 10 47"

[[params.footer.contacto2Item]]
title="Ayuntamiento de Alburquerque"
icon = "fa fa-map-marker"
content = "Calle San Mateo, 1 - 06510 Alburquerque (Badajoz)"

[[params.footer.contacto2Item]]
title="Email"
icon = "fa fa-envelope"
content = "webmaster@alburquerque.es"

# Redes sociales
[[params.footer.socialLink]]
icon = "fa fa-facebook"
link = "https://www.facebook.com/AgenciaDeDesarrolloLocalDeAlburquerque/"

[[params.footer.socialLink]]
icon = "fa fa-twitter"
link = "https://twitter.com/home?status=Est%C3%A1%20usando%20Alburquerque%20Experience!"

[[params.footer.socialLink]]
icon = "fa fa-instagram"
link = "https://twitter.com/BaylioMagazine"

#Footer Copyright Text
[params.footerCopyright]
enable = true
Text = "Copyright © 2019 - Todos los derechos reservados. Ayuntamiento de Alburquerque."