baseURL = "http://example.org/"
languageCode = "en-us"
title = "Restaurant Theme By Themefisher"
theme="restaurant-hugo"
summaryLength = "7"



# Menu
[menu]
	
	[[menu.nav]]
    name = "Inicio"
    URL = "#inicio"
    weight = 1

    [[menu.nav]]
    name = "Mi perfil"
    URL = "#miperfil"
    weight = 6

    [[menu.nav]]
    name = "Espacios"
    URL = "#espacios"
    weight = 2

    [[menu.nav]]
    name = "Bonos"
    URL = "#bonos"
    weight = 3

    [[menu.nav]]
    name = "Newsletter"
    URL = "#subscribe"
    weight = 4

    [[menu.nav]]
    name = "Contacto"
    URL = "#contacto"
    weight = 5

    [[menu.nav]]
    name = "Acceso"
    URL = "/acceso"
    weight = 6

    [[menu.nav]]
    name = "Registro"
    URL = "/registro"
    weight = 6

# Global Settings
[params]
logo = "images/logoex.png"


[params.inicio]
enable = true
[params.heroImg ] 
url =  "images/castillo4.jpg" 


#gallery item

[params.gallery]
enable = true
title= "Próximos <span>Eventos</span>"

[[params.gallery.item]]
img = "images/slider/playmobil.jpg"

[[params.gallery.item]]
img = "images/slider/medieval2.jpg"

[[params.gallery.item]]
img = "images/slider/contempopranea.jpg"

[[params.gallery.item]]
img = "images/slider/balonmano.jpg"

[[params.gallery.item]]
img = "images/slider/feriaganao.jpg"

[[params.gallery.item]]
img = "images/slider/carrera.jpg"

[[params.gallery.item]]
img = "images/slider/semanasanta.jpg"


[params.miperfil]
enable = true
title= "Mi <span> Perfil</span>"
bgImage = "images/cooker-img.png"
description= "Mis Bonos - Mis Reservas - Mis Datos"




#bonos Menu

[params.bonos]
enable = true
title = "Bonos  <span>Piscina</span> y <span>Gym</span>"
description= "Las instalaciones de la piscina estarán abiertas de lunes a domingo en horario de 12:00 a 21:00 h. y las instalaciones del gym de lunes a viernes de 12:00 a 14:00 y de 17:00 a 22:30 h. y los sábados de 12:00 a 14:00"
subtitle = "Precios"

[[params.bonos.item]]
title="70 entradas"
description= ""
bonos = "50.00 €"

[[params.bonos.item]]
title="25 entradas"
description= ""
bonos = "25.00 €"

[[params.bonos.item]]
title="10 entradas"
description= ""
bonos = "12.00 €"

[[params.bonos.item]]
title="Diaria Adulto"
description= ""
bonos = "3.00 €"

[[params.bonos.item]]
title="Diaria Menores y Pensionistas"
description= "Se entiende por menores a las personas que tengan menos de 15 años. Los niños hasta 4 años tendrán entrada gratuita."
bonos = "1.50 €"



#subscription

[params.subscription]
enable = true
title= "SUBSCRIBETE a nuestra <span>NEWSLETTER</span>"
description = "Subscríbete para no perderte nada y estar al día de todo lo que pase en Alburquerque"

#Mailchimp subscription configaration 
formAction = "https://themefisher.us9.list-manage.com/subscribe/post?u=f95ece2732a6e9925f2e70a61&amp;id=b1e227529e"
formName = "b_f95ece2732a6e9925f2e70a61_b1e227529e"

#Contacto 

[params.contacto]
enable = true
title= "<span>Contacto </span>"
subtitle= "Escríbenos"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod"


#Footer 

[params.footer]
enable = true
contactoInfoTitle = "INFO <span>CONTACTO</span>"
espaciosTitle = "MI <span>PERFIL</span>"
galleryTitle = "Fotos <span>Eventos</span>"
socialTitle = "REDES <span>SOCIALES</span>"

[[params.footer.contactoItem]]
title="Teléfono"
icon = "fa fa-phone"
content = "016742 323313"

[[params.footer.contactoItem]]
title="Dirección"
icon = "fa fa-map-marker"
content = "2046 Blue Spruce Lane Laurel Canada"

[[params.footer.contactoItem]]
title="Email"
icon = "fa fa-envelope"
content = "rest@gmail.com - rest@mail.ru"

[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/themefisher"


[[params.footer.socialLink]]
icon = "twitter"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "dribbble"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://fb.com/themefisher"


#Footer Copyright

#Footer Copyright Text
[params.footerCopyright]
enable = true
Text = "Copyright 2019 - Todos los derechos reservados. Ayuntamiento de Alburquerque."




#blog 
[params.espacios]
enable = true
title = "<span>Reserva</span> de <span>Espacios</span>"

[params.blog]
enable = true
title = "Get The Latest On What We're doing"
subtitle = "Catch up with us, anytime and anywhere" 









